"""
Generate sql/03_raw_enverus_ddl.sql by calling Enverus' v3.ddl() for each
dataset we want, then prefixing every table with the raw_enverus schema.

The enverus-developer-api package exposes v3.ddl(dataset, database="pg")
which returns an authoritative CREATE TABLE statement for any dataset
they expose. Using it keeps us perfectly in sync with Enverus's schema.

Usage:
    # Requires ENVERUS_SECRET_KEY in .env
    python -m scripts.generate_enverus_ddl

Output:
    sql/03_raw_enverus_ddl.sql
"""
from __future__ import annotations

import argparse
import logging
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv
from enverus_developer_api import DeveloperAPIv3

logger = logging.getLogger(__name__)

# Datasets to ingest. Start small; add as needed.
# Names must match what Enverus exposes - check their docs at
# https://app.enverus.com/direct/#/api/explorer/v3/gettingStarted
MVP_DATASETS: list[str] = [
    "wells",
    "production",
    # Add others as needed, e.g. "rigs", "permits", "casings"
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("sql/03_raw_enverus_ddl.sql"),
        help="Where to write the generated DDL (default: sql/03_raw_enverus_ddl.sql)",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        default=MVP_DATASETS,
        help=f"Datasets to fetch DDL for (default: {' '.join(MVP_DATASETS)})",
    )
    return parser.parse_args()


# Match `CREATE TABLE <name>` with optional double-quotes around the name.
CREATE_TABLE_RE = re.compile(
    r'CREATE TABLE\s+(?:"(?P<quoted>[A-Za-z0-9_]+)"|(?P<bare>[A-Za-z0-9_]+))',
    re.IGNORECASE,
)


def rewrite_to_raw_enverus(ddl: str, dataset_name: str) -> str:
    """Prefix the CREATE TABLE name with `raw_enverus.` schema.

    Enverus's ddl() returns a single CREATE TABLE statement per call. We rewrite
    the table name so it lands in our raw_enverus schema. Index and constraint
    names are not rewritten - they're scoped to the schema automatically.
    """
    match = CREATE_TABLE_RE.search(ddl)
    if not match:
        raise ValueError(f"Could not find CREATE TABLE in DDL for {dataset_name}")

    original_name = match.group("quoted") or match.group("bare")
    # Use the dataset name directly so we get raw_enverus.wells, not
    # raw_enverus.<whatever Enverus internally called it>
    replacement = f'CREATE TABLE raw_enverus."{dataset_name}"'
    return ddl[: match.start()] + replacement + ddl[match.end() :]


def fetch_and_rewrite(client: DeveloperAPIv3, dataset: str) -> str:
    logger.info("Fetching DDL for dataset: %s", dataset)
    ddl = client.ddl(dataset, database="pg")
    if not ddl or not ddl.strip():
        raise RuntimeError(f"Empty DDL returned for dataset: {dataset}")
    rewritten = rewrite_to_raw_enverus(ddl, dataset)
    return rewritten.strip()


def generate(output_file: Path, datasets: list[str]) -> None:
    load_dotenv()
    secret_key = os.getenv("ENVERUS_SECRET_KEY")
    if not secret_key:
        sys.exit("ENVERUS_SECRET_KEY not found in .env or environment")

    client = DeveloperAPIv3(secret_key=secret_key)

    output_lines: list[str] = [
        "-- =============================================================================",
        "-- raw_enverus DDL - generated by calling Enverus v3.ddl() per dataset",
        f"-- Datasets included: {', '.join(datasets)}",
        "-- ",
        "-- DO NOT EDIT BY HAND. Regenerate with scripts/generate_enverus_ddl.py.",
        "-- =============================================================================",
        "",
    ]

    for dataset in datasets:
        try:
            ddl = fetch_and_rewrite(client, dataset)
        except Exception:
            logger.exception("Failed to generate DDL for %s; skipping", dataset)
            continue

        output_lines.append(f"-- ----- dataset: {dataset} -----")
        output_lines.append(ddl)
        if not ddl.rstrip().endswith(";"):
            output_lines[-1] = output_lines[-1] + ";"
        # Add an ingested_at column so we can trace when each row was loaded
        output_lines.append(
            f'ALTER TABLE raw_enverus."{dataset}" '
            f'ADD COLUMN IF NOT EXISTS ingested_at timestamptz NOT NULL DEFAULT now();'
        )
        output_lines.append("")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("\n".join(output_lines), encoding="utf-8")
    logger.info("Wrote %s", output_file)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    args = parse_args()
    generate(args.output, args.datasets)


if __name__ == "__main__":
    main()
