-- =============================================================================
-- Oil & Gas Database - Initial DDL (v3)
-- Target: PostgreSQL 16+ with PostGIS
--
-- CHANGES FROM v2:
--   * raw_novi.* tables are now generated from Novi's shipped schema.postgres.sql
--     (use scripts/generate_novi_ddl.py to produce sql/02_raw_novi_ddl.sql)
--   * raw_enverus.* tables are now generated by Enverus's own v3.ddl() function
--     (use scripts/generate_enverus_ddl.py to produce sql/03_raw_enverus_ddl.sql)
--   * curated.wells and curated.production are intentionally deferred until
--     both raw schemas are populated, so we can join on real column names.
--
-- RUN ORDER:
--   1. Run this file first (creates extensions, schemas, meta).
--   2. After first Novi bulk sync, run scripts/generate_novi_ddl.py, then
--      execute sql/02_raw_novi_ddl.sql.
--   3. Once Enverus credentials are in .env, run scripts/generate_enverus_ddl.py,
--      then execute sql/03_raw_enverus_ddl.sql.
--   4. Then write sql/04_curated.sql using the now-known column names from
--      both raw schemas.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Extensions
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- -----------------------------------------------------------------------------
-- 2. Schemas
--    raw_enverus / raw_novi : mirror what each source ships, untransformed
--    curated                : merged canonical model (built later)
--    meta                   : ETL logging and control
-- -----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS raw_enverus;
CREATE SCHEMA IF NOT EXISTS raw_novi;
CREATE SCHEMA IF NOT EXISTS curated;
CREATE SCHEMA IF NOT EXISTS meta;


-- -----------------------------------------------------------------------------
-- 3. ETL logging
-- -----------------------------------------------------------------------------
CREATE TABLE meta.etl_log (
    etl_log_id       BIGSERIAL PRIMARY KEY,
    source           TEXT NOT NULL,            -- 'enverus' or 'novi'
    table_name       TEXT NOT NULL,            -- the table touched, or 'bulk_sync', 'refresh', etc.
    run_started_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    run_finished_at  TIMESTAMPTZ,
    status           TEXT,                     -- 'running' | 'success' | 'failed'
    rows_inserted    BIGINT,
    rows_updated     BIGINT,
    rows_deleted     BIGINT,
    bytes_downloaded BIGINT,                   -- useful for Novi bulk runs
    export_date      TEXT,                     -- Novi's ExportDate of the sync, if applicable
    error_message    TEXT
);

CREATE INDEX idx_etl_log_started ON meta.etl_log (run_started_at DESC);
CREATE INDEX idx_etl_log_source  ON meta.etl_log (source, table_name, run_started_at DESC);


-- -----------------------------------------------------------------------------
-- 4. Refresh function (stub until curated layer is built)
-- After curated views/tables exist, edit this to refresh them.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION curated.refresh_all()
RETURNS void AS $$
BEGIN
    -- After curated layer is built, add refreshes here, e.g.:
    --   REFRESH MATERIALIZED VIEW CONCURRENTLY curated.wells;
    --   REFRESH MATERIALIZED VIEW CONCURRENTLY curated.production;
    RAISE NOTICE 'curated.refresh_all() called - no curated objects defined yet';
END;
$$ LANGUAGE plpgsql;


-- =============================================================================
-- DONE.
-- Next: run the two DDL generator scripts, then build the curated layer.
-- =============================================================================
