-- =============================================================================
-- raw_novi DDL - generated from Novi's shipped schema.postgres.sql
-- Source file: data\us-horizontals\All basins\All subbasins\Bulk\schema.postgres.sql
-- Tables included: ForecastWellMonths, WellDetails, WellMonths, WellSpacing, Wells
-- 
-- DO NOT EDIT BY HAND. Regenerate with scripts/generate_novi_ddl.py.
-- =============================================================================

CREATE TABLE raw_novi."Wells" (
    "API10" varchar(32) NOT NULL,
    "IsHorizontalWell" bool NOT NULL,
    "WellName" varchar(64) NULL,
    "WellType" varchar(16) NOT NULL,
    "OriginalOperator" varchar(64) NULL,
    "CurrentOperator" varchar(64) NULL,
    "CurrentOperatorEntity" varchar(64) NULL,
    "LeaseID" varchar NULL,
    "Basin" varchar(36) NOT NULL,
    "Subbasin" varchar(36) NOT NULL,
    "State" varchar(16) NOT NULL,
    "StateCode" int4 NOT NULL,
    "County" varchar(32) NULL,
    "CountyUnique" varchar(32) NULL,
    "CountyCode" varchar(5) NULL,
    "Field" varchar(64) NULL,
    "Formation" varchar(64) NOT NULL,
    "ReportedFormation" varchar(64) NULL,
    "ReportedFormationRaw" varchar(1024) NULL,
    "GridFormation" varchar(64) NULL,
    "SHLLatitude" float8 NULL,
    "SHLLongitude" float8 NULL,
    "BHLLatitude" float8 NULL,
    "BHLLongitude" float8 NULL,
    "HasPLSSData" bool NOT NULL,
    "Meridian" varchar(36) NULL,
    "Township" varchar(5) NULL,
    "Range" varchar(5) NULL,
    "Section" int4 NULL,
    "Quarter" varchar(10) NULL,
    "TXBlock" varchar(36) NULL,
    "TXSurvey" varchar(36) NULL,
    "TXAbstract" varchar(36) NULL,
    "TVD" int4 NULL,
    "MD" int4 NULL,
    "WellboreLocations" int4 NOT NULL,
    "SpudDate" date NULL,
    "DrillingEndDate" date NULL,
    "DrillingCompletionDate" date NULL,
    "FirstCompletionDate" date NULL,
    "FirstProductionDate" date NULL,
    "HasAccurateFirstProductionDate" bool NOT NULL,
    "LastReportedMonth" date NULL,
    "PluggedDate" date NULL,
    "HasProductionSharing" bool NOT NULL,
    "LateralLength" int4 NULL,
    "LateralLengthSource" varchar NULL,
    "FirstCompletionProppantMass" int4 NULL,
    "FirstCompletionFluidVolume" int4 NULL,
    "FirstCompletionStages" int4 NULL,
    "Refrac" int4 NOT NULL,
    "Altitude" int4 NULL,
    "LastWellStatus" varchar NULL,
    "WellStatus" text NOT NULL,
    "WellStatusReportedNormalized" varchar(64) NULL,
    "ReportedWellStatus" varchar(64) NULL,
    "DirectionalSurveyIsPlanned" bool NULL,
    "ReportedSlant" varchar NULL,
    "ReportedSlantNormalized" varchar(36) NULL,
    "SlantCalculated" varchar(32) NULL,
    "PermitID" varchar(32) NULL,
    "PermitSubmitDate" date NULL,
    "PermitApprovedDate" date NULL,
    "PermitExpirationDate" date NULL,
    "UpperPerforation" int8 NULL,
    "LowerPerforation" int8 NULL,
    "PerforationInterval" int8 NULL,
    "WellboreLateralLength" int4 NULL,
    "IsSyntheticApi" bool NOT NULL,
    "CreatedAt" timestamp NULL,
    "ModifiedAt" timestamp NULL,
    "DeletedAt" timestamp NULL,
    CONSTRAINT "Wells_pkey" PRIMARY KEY ("API10")
,
    "ingested_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE raw_novi."WellSpacing" (
    "API10" varchar(32) NOT NULL,
    "Basin" varchar(36) NOT NULL,
    "ClosestWellXY" float8 NOT NULL,
    "WellsInRadius" int4 NOT NULL,
    "ClosestTwoAvgXY" float8 NOT NULL,
    "WellsInRadiusAvgXY" float8 NOT NULL,
    "IsChild" bool NOT NULL,
    "ParentCount" int4 NOT NULL,
    "ParentDaysOnline" float8 NOT NULL,
    "LateralCloserXY" float8 NOT NULL,
    "StaggerCloserTangent" float8 NOT NULL,
    "StackCloserZ" int8 NOT NULL,
    "BoundednessScore" int8 NOT NULL,
    "CreatedAt" timestamp NULL,
    "ModifiedAt" timestamp NULL,
    "DeletedAt" timestamp NULL,
    CONSTRAINT "WellSpacing_pkey" PRIMARY KEY ("API10")
,
    "ingested_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE raw_novi."WellMonths" (
    "API10" varchar(32) NOT NULL,
    "Year" int4 NOT NULL,
    "Month" int4 NOT NULL,
    "Date" date NOT NULL,
    "Operator" varchar(64) NULL,
    "OperatorEntity" varchar(64) NULL,
    "OilPerDay" float8 NULL,
    "OilPerMonth" int4 NULL,
    "CumulativeOil" int4 NOT NULL,
    "GasPerDay" float8 NULL,
    "GasPerMonth" int4 NULL,
    "CumulativeGas" int4 NOT NULL,
    "WaterPerDay" float8 NULL,
    "WaterPerMonth" int4 NULL,
    "CumulativeWater" int4 NOT NULL,
    "ProducingDays" int4 NULL,
    "CumulativeProducingDays" int4 NOT NULL,
    "MonthsOnProduction" int4 NOT NULL,
    "FlaredGasPerDay" float8 NULL,
    "FlaredGasPerMonth" int4 NULL,
    "CumulativeFlaredGas" int4 NULL,
    "Basin" varchar(36) NOT NULL,
    "Subbasin" varchar(36) NOT NULL,
    "IsOilFromProductionSharing" bool NOT NULL,
    "IsGasFromProductionSharing" bool NOT NULL,
    "IsGasFlaredFromProductionSharing" bool NOT NULL,
    "IsWaterFromProductionSharing" bool NOT NULL,
    "CreatedAt" timestamp NULL,
    "ModifiedAt" timestamp NULL,
    "DeletedAt" timestamp NULL,
    CONSTRAINT "WellMonths_pkey" PRIMARY KEY ("API10", "Year", "Month")
,
    "ingested_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE raw_novi."WellDetails" (
    "API10" varchar(32) NOT NULL,
    "IsHorizontalWell" bool NOT NULL,
    "Direction" varchar(32) NULL,
    "WellName" varchar(64) NULL,
    "WellType" varchar(16) NOT NULL,
    "OriginalOperator" varchar(64) NULL,
    "CurrentOperator" varchar(64) NULL,
    "CurrentOperatorEntity" varchar(64) NULL,
    "LeaseID" varchar NULL,
    "Basin" varchar(36) NOT NULL,
    "Subbasin" varchar(36) NOT NULL,
    "State" varchar(16) NOT NULL,
    "StateCode" int4 NOT NULL,
    "County" varchar(32) NULL,
    "CountyUnique" varchar(32) NULL,
    "CountyCode" varchar(5) NULL,
    "Field" varchar(64) NULL,
    "Formation" varchar(64) NOT NULL,
    "ReportedFormation" varchar(64) NULL,
    "ReportedFormationRaw" varchar(1024) NULL,
    "GridFormation" varchar(64) NULL,
    "SHLLatitude" float8 NULL,
    "SHLLongitude" float8 NULL,
    "BHLLatitude" float8 NULL,
    "BHLLongitude" float8 NULL,
    "LPLatitude" float8 NULL,
    "LPLongitude" float8 NULL,
    "MPLatitude" float8 NULL,
    "MPLongitude" float8 NULL,
    "HasPLSSData" bool NOT NULL,
    "Meridian" varchar(36) NULL,
    "Township" varchar(5) NULL,
    "Range" varchar(5) NULL,
    "Section" int4 NULL,
    "Quarter" varchar(10) NULL,
    "TXBlock" varchar(36) NULL,
    "TXSurvey" varchar(36) NULL,
    "TXAbstract" varchar(36) NULL,
    "TVD" int4 NULL,
    "MD" int4 NULL,
    "WellboreLocations" int4 NOT NULL,
    "PermitID" varchar(32) NULL,
    "PermitSubmitDate" date NULL,
    "PermitApprovedDate" date NULL,
    "PermitExpirationDate" date NULL,
    "SpudDate" date NULL,
    "DrillingEndDate" date NULL,
    "DrillingCompletionDate" date NULL,
    "FirstCompletionDate" date NULL,
    "FirstProductionDate" date NULL,
    "HasAccurateFirstProductionDate" bool NOT NULL,
    "FirstProductionDateFromState" date NULL,
    "FirstProductionYear" int4 NULL,
    "LastReportedMonth" date NULL,
    "LastReportedMonthsOnProduction" int4 NULL,
    "LastWellStatus" varchar NULL,
    "WellStatus" text NOT NULL,
    "WellStatusReportedNormalized" varchar(64) NULL,
    "ReportedWellStatus" varchar(64) NULL,
    "PluggedDate" date NULL,
    "HasProductionSharing" bool NOT NULL,
    "LateralLength" int4 NULL,
    "LateralLengthSource" varchar NULL,
    "FirstCompletionProppantMass" int4 NULL,
    "FirstCompletionFluidVolume" int4 NULL,
    "FirstCompletionStages" int4 NULL,
    "Refrac" int4 NOT NULL,
    "FirstCompletionStages_AvgSpacing" int4 NULL,
    "FirstCompletionProppantLbsPerGal" float4 NULL,
    "FirstCompletionProppantLbsPerFt" int4 NULL,
    "SoakTimeDays" int4 NULL,
    "Altitude" int4 NULL,
    "Cum12MOil" int4 NULL,
    "Cum12MGas" int4 NULL,
    "Cum12MWater" int4 NULL,
    "Cum12MBOE" int4 NULL,
    "Cum24MOil" int4 NULL,
    "Cum24MGas" int4 NULL,
    "Cum24MWater" int4 NULL,
    "Cum24MBOE" int4 NULL,
    "CumLifeOil" int4 NULL,
    "CumLifeGas" int4 NULL,
    "CumLifeWater" int4 NULL,
    "CumLifeBOE" int4 NULL,
    "CumLifeGOR" float8 NULL,
    "EUR20YROil" int4 NULL,
    "EUR20YRGas" int4 NULL,
    "EUR20YRWater" int4 NULL,
    "EUR20YRBOE" int4 NULL,
    "EUR30YROil" int4 NULL,
    "EUR30YRGas" int4 NULL,
    "EUR30YRWater" int4 NULL,
    "EUR30YRBOE" int4 NULL,
    "EUR50YROil" int4 NULL,
    "EUR50YRGas" int4 NULL,
    "EUR50YRWater" int4 NULL,
    "EUR50YRBOE" int4 NULL,
    "PeakMonthOil" int4 NULL,
    "PeakMonthGas" int4 NULL,
    "PeakMonthWater" int4 NULL,
    "PeakMonthBOE" int4 NULL,
    "PeakMonthOilRate" int4 NULL,
    "PeakMonthGasRate" int4 NULL,
    "PeakMonthWaterRate" int4 NULL,
    "PeakMonthBOERate" int4 NULL,
    "SpacingIsChild" bool NULL,
    "SpacingClosestWellXY" float8 NULL,
    "DirectionalSurveyIsPlanned" bool NULL,
    "ReportedSlant" varchar NULL,
    "ReportedSlantNormalized" varchar(36) NULL,
    "SlantCalculated" varchar(32) NULL,
    "UpperPerforation" int8 NULL,
    "LowerPerforation" int8 NULL,
    "PerforationInterval" int8 NULL,
    "WellboreLateralLength" int4 NULL,
    "CreatedAt" timestamp NULL,
    "ModifiedAt" timestamp NULL,
    "DeletedAt" timestamp NULL,
    CONSTRAINT "WellDetails_pkey" PRIMARY KEY ("API10")
,
    "ingested_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE raw_novi."ForecastWellMonths" (
    "API10" varchar(32) NOT NULL,
    "Date" date NOT NULL,
    "MonthsOnProduction" int2 NOT NULL,
    "IsForecasted" bool NOT NULL,
    "Basin" varchar(36) NOT NULL,
    "Subbasin" varchar(36) NOT NULL,
    "OilPerDay" float8 NULL,
    "OilPerMonth" int4 NULL,
    "CumulativeOil" int4 NULL,
    "GasPerDay" float8 NULL,
    "GasPerMonth" int4 NULL,
    "CumulativeGas" int4 NULL,
    "WaterPerDay" float8 NULL,
    "WaterPerMonth" int4 NULL,
    "CumulativeWater" int4 NULL,
    "CreatedAt" timestamp NULL,
    "ModifiedAt" timestamp NULL,
    "DeletedAt" timestamp NULL,
    CONSTRAINT "ForecastWellMonths_pkey" PRIMARY KEY ("API10", "Date")
,
    "ingested_at" timestamptz NOT NULL DEFAULT now()
);
