-- =============================================================================
-- 12 — RETIRED (2026-07-10, Snowflake-share migration phase 8). DO NOT RUN.
--
-- This file built the original curated Novi Intelligence layer
-- (curated.intel_locations / intel_arps / intel_forecast) from the
-- raw_novi_intel file-drop tables. Those source tables were dropped on
-- 2026-07-10; the curated intel layer is now built by
--
--     sql/29_curated_intel_sf.sql        (from the raw_intel Snowflake mirror, sql/27)
--     python -m scripts.load_intel_sf --curated
--
-- sql/29 preserves this file's output contract (same objects, same columns,
-- irr_pct in percent, mop = ip_day/30) — downstream sql/19/21/22/25/30 and the
-- erebor app were unaffected by the swap. The last real body of this file is
-- at commit 2989c92. The number stays reserved so the sql/NN sequence remains
-- canonical.
-- =============================================================================
