-- =============================================================================
-- 13 — RETIRED (2026-07-10, Snowflake-share migration phase 8). DO NOT RUN.
--
-- This file defined raw_novi_intel.pud_attrs, the PUD ML tier/score attributes
-- parsed from the Other_ML_PUD_Oil + Undrilled_Rock_Quality shapefiles in the
-- quarterly file drop. The table was dropped on 2026-07-10; the same ML
-- attributes (spacing/depletion/completion scores + tiers, rock quality) now
-- come from the Snowflake share:
--
--     raw_intel.well_ml_score + raw_intel.well_rock_quality   (sql/27,
--     loaded by scripts/load_intel_sf.py --ml; joined into
--     curated.intel_locations by sql/29 — coverage now includes PDP too)
--
-- The last real body of this file is at commit 2989c92. The number stays
-- reserved so the sql/NN sequence remains canonical.
-- =============================================================================
